### ISSUE TITLE
PhotoViewAttacher not found on Android 4.2.2 ?

### ISSUE THREAD

**Issue by anthony3444** [chrisbanes/PhotoView#336]
Hi !

I have CustomPhotoView component:

```
public class CustomPhotoView extends FrameLayout {

    private ImageView mDefaultImageView;
    private PhotoView mPhotoImageView;

    public CustomPhotoView(Context context) {
        super(context);
        init();
    }

    public CustomPhotoView(Context context, AttributeSet attrs) {
        super(context, attrs);
        treatAttibutes(context, attrs);
        init();
    }

    public CustomPhotoView(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        treatAttibutes(context, attrs);
        init();
    }

    protected void treatAttibutes(Context context, AttributeSet attrs) {}

    protected void init() {
        // Create and setup image views
        mDefaultImageView = new ImageView(getContext());
        mPhotoImageView = new PhotoView(getContext());

    ...
```
I use the last PhotoView library: compile 'com.github.chrisbanes.photoview:library:1.2.4'

It works perfectly on my S5 (Android 5.1), but on my Genymotion with Android 4.4.4 it's failed on line:

`mPhotoImageView = new PhotoView(getContext());`

The error is: 
**java.lang.NoClassDefFoundError: uk.co.senab.photoview.PhotoViewAttacher**

Thank you very much for your help!

**Comment by waitray** [comment]
I encounted the same problem,can somebody help?

**Comment by anthony3444** [comment]
The problem was linked with multidex in my Gradle.

The correct way is to set in Gradle:
// Enabling multidex support.
multiDexEnabled true

And this in my Application class:
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

Check this link too:  http://stackoverflow.com/questions/36547087/android-java-lang-noclassdeffounderror-on-the-release-apk/36547147?noredirect=1#comment60698278_36547147

**Comment by waitray** [comment]
I slove it too. add code
 @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

then it is all right!

**Comment by waitray** [comment]
thx @anthony3444

**Comment by Jawnnypoo** [comment]
Happy you could both resolve it!
